version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
    - dependency-name: "ch.qos.logback:logback-*"
      # start from 1.4.x JDK 11 is required, but dumper's minimal is JDK 8
      versions: [ ">=1.4.x" ]
