version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
      timezone: "UTC"
    ignore:
      - dependency-name: " ch.qos.logback:logback-*"
        # start from 1.4.x JDK 11 is required, but dumper's minimal is JDK 8
        versions: [">=1.4.x"]
