[connectionConfig]
connectionType = "POSTGRESQL"
database = "validation"
driver = "/usr/local/google/home/nehanene/Downloads/postgresql-42.7.5.jar"
user = "testuser"
password = "testpassword"
host = "localhost"
port = 5432

[bigqueryConfig]
projectId = "bqms-validation-sandbox-153923"
dataset = "validation"
resultsTable = "project.dataset.results"

[tableConfig]
employees = "validation.employees_invalid"
primaryKey = "id"
