WHENEVER SQLERROR EXIT 1;

-- Set SQL*Plus environment options for CSV output
SET HEADING ON
SET FEEDBACK OFF
SET TERMOUT OFF
SET ECHO OFF
SET PAGESIZE 0
SET LINESIZE 32767
SET TRIMOUT ON
set UNDERLINE OFF
SET VERIFY OFF
SET MARKUP CSV ON DELIMITER ',' QUOTE OFF
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';
ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS';

-- Accept the input file name and output file name as arguments
DEFINE INPUT_SCRIPT = &1
DEFINE OUTPUT_FILE = &2
DEFINE DURATION_DAYS = &3

-- Spool the output to the specified CSV file
SPOOL &OUTPUT_FILE
@&INPUT_SCRIPT &DURATION_DAYS;
/
SPOOL OFF;

-- Reset SQL*Plus environment options
SET ECHO ON
SET VERIFY ON
SET FEEDBACK ON
SET TERMOUT ON;
SET PAGESIZE 50;
SET LINESIZE 80;

-- Exit successfully
EXIT SUCCESS
